### PR TITLE
Update index.js

### PR DESCRIPTION
**Pull request by mhussa**
tiny typo :)

### CODE REVIEW

**Comment by jorgebucaran** [comment]
What happened to https://github.com/lukejacksonn/hyperapp-pwa/pull/6? 🤔

**Comment by mhussa** [comment]
no idea, cloned it, ran it and found the obvious hidden coding puzzle.

**Comment by jorgebucaran** [comment]
https://github.com/lukejacksonn/hyperapp-pwa/pull/6 should've fixed the bug, but the issue is just closed lol.

**Comment by mhussa** [comment]
mergetastic ;)

**Comment by jorgebucaran** [comment]
It seems this bug always finds a way to creep back into the app. Mindboggling.

**Comment by lukejacksonn** [comment]
Yeh.. wtf! I was on vacation when that issue came in. Must have thought it was a PR and closed it thinking it was a merge 😅 whoops. Thanks you all 🙇

**Pull request merged**
